import { useState } from "react";

import { Box } from "@mui/material";

import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import MainContent from "../components/MainContent";
import Snackbar from "@mui/material/Snackbar";
import Alert from "@mui/material/Alert";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function Home() {

  const [sql, setSql] = useState("");
  const [results, setResults] = useState([]);
  const [rowCount, setRowCount] = useState(0);
  const [lastQuestion, setLastQuestion] = useState("");
  const [success, setSuccess] = useState(false);

  const [history, setHistory] = useState(() => {
    const saved = localStorage.getItem("queryHistory");
    return saved ? JSON.parse(saved) : [];
  });

  const [bookmarks, setBookmarks] = useState(() => {
    const saved = localStorage.getItem("bookmarks");
    return saved ? JSON.parse(saved) : [];
  });

  const [snackbar, setSnackbar] = useState({
    open: false,
    message: "",
    severity: "success",
});



  const addToHistory = (question) => {

    const historyItem = {
      question,
      timestamp: new Date().toLocaleString(),
    };

    const updatedHistory = [
      historyItem,
      ...history.filter(
        (item) => item.question !== question
      ),
    ].slice(0, 10);

    setHistory(updatedHistory);

    localStorage.setItem(
      "queryHistory",
      JSON.stringify(updatedHistory)
    );
  };



  const addBookmark = (question, sql) => {

    const bookmark = {
        question,
        sql,
        timestamp: new Date().toLocaleString(),
    };

    const updatedBookmarks = [
        bookmark,
        ...bookmarks.filter(
            item => item.question !== question
        ),
    ];

    setBookmarks(updatedBookmarks);

    localStorage.setItem(
        "bookmarks",
        JSON.stringify(updatedBookmarks)
    );
  };


    const showSnackbar = (
      message,
        severity = "success"
    ) => {

        setSnackbar({
            open: true,
            message,
            severity,
        });

    };

    const handleCloseSnackbar = () => {

        setSnackbar(prev => ({
            ...prev,
            open: false,
        }));

    };


    const exportCSV = () => {

      if (!results.length) return;

      const headers = Object.keys(results[0]);

      const csv = [

          headers.join(","),

          ...results.map(row =>
              headers.map(h => `"${row[h]}"`).join(",")
          ),

      ].join("\n");

      const blob = new Blob(
          [csv],
          {
              type: "text/csv",
          }
      );

      const url = URL.createObjectURL(blob);

      const a = document.createElement("a");

      a.href = url;

      a.download = "aml_results.csv";

      a.click();

      URL.revokeObjectURL(url);

      showSnackbar(
          "CSV exported successfully!"
      );

  };


const exportPDF = () => {

    if (!results.length) return;

    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("AML Investigation Report", 14, 20);

    doc.setFontSize(11);

    doc.text(
        `Generated: ${new Date().toLocaleString()}`,
        14,
        30
    );

    doc.text(
        `Question: ${lastQuestion}`,
        14,
        40
    );

    doc.text(
        `Rows Returned: ${rowCount}`,
        14,
        50
    );

    doc.text(
        "Generated SQL:",
        14,
        62
    );

    const sqlLines = doc.splitTextToSize(sql, 180);

    doc.text(sqlLines, 14, 70);

    const headers = [Object.keys(results[0])];

    const body = results.map(row =>
        Object.values(row)
    );

    autoTable(doc, {

        head: headers,

        body,

        startY: 90,

        styles: {
            fontSize: 8,
        },

    });

    const finalY =
        doc.lastAutoTable.finalY + 15;

    doc.setFontSize(10);

    doc.text(
        "Generated by Fraud Detection & Compliance Reporting Dashboard",
        14,
        finalY
    );

    doc.text(
        "Accenture Internship Project",
        14,
        finalY + 8
    );

    doc.save("AML_Investigation_Report.pdf");

    showSnackbar(
        "SAR PDF exported successfully!"
    );

};




  return (
    <>
      <Navbar />

      <Box
        sx={{
          display: "flex",
          height: "calc(100vh - 64px)",
        }}
      >
        <Sidebar
            history={history}
            bookmarks={bookmarks}
        />

        <MainContent
          sql={sql}
          setSql={setSql}
          results={results}
          setResults={setResults}
          rowCount={rowCount}
          setRowCount={setRowCount}
          lastQuestion={lastQuestion}
          setLastQuestion={setLastQuestion}
          success={success}
          setSuccess={setSuccess}
          addToHistory={addToHistory}
          addBookmark={addBookmark}
          showSnackbar={showSnackbar}
          exportCSV={exportCSV}
          exportPDF={exportPDF}
        />
      </Box>


    <Snackbar
        open={snackbar.open}
        autoHideDuration={3000}
        onClose={handleCloseSnackbar}
        anchorOrigin={{
            vertical: "bottom",
            horizontal: "right",
        }}
    >
        <Alert
            severity={snackbar.severity}
            variant="filled"
            onClose={handleCloseSnackbar}
        >
            {snackbar.message}
        </Alert>
    </Snackbar>
    </>
  );
}